services:
  # docker compose exec db psql --user postgres angel
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: 'timescale/timescaledb:latest-pg17'
    restart: unless-stopped
    volumes:
      - 'timescaledb:/var/lib/postgresql/data'
  # To debug, run: 
  #   docker compose down web
  #   docker compose run --service-ports web /bin/bash
  #   iex --dbg pry -S mix phx.server
  web:
    build: .
    depends_on:
      - db
    environment:
      MIX_ENV: ${ENV}
    env_file:
      - .env
    ports:
      - '11000:4000'
      - '8012:4000'
    volumes:
      - .:/app
  graphite:
   build:
    context: ./graphite
    dockerfile: Dockerfile
    args:
      python_binary: python3
   volumes:
    - ./graphite/conf/opt/graphite/conf:/opt/graphite/conf
    - ./graphite/conf/opt/graphite/storage:/opt/graphite/storage
volumes:
  pgdata:
  timescaledb:

