version: '3.6'
services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: 'postgres:17-alpine'
    restart: unless-stopped
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  web:
    build: .
    depends_on:
      - db
    environment:
      MIX_ENV: prod
    env_file:
      - .env
    ports:
      - '8012:4000'
    volumes:
      - .:/app
  graphite:
   build:
    context: ./graphite
    dockerfile: Dockerfile
    args:
      python_binary: python3
   volumes:
    - ./graphite/conf/opt/graphite/conf:/opt/graphite/conf
    - ./graphite/conf/opt/graphite/storage:/opt/graphite/storage
volumes:
  pgdata:

